/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from '../../src/parallax.module';
class ParallaxModuleInjector extends import0.ɵNgModuleInjector<import1.ParallaxModule> {
  _ParallaxModule_0:import1.ParallaxModule;
  constructor(parent:import0.Injector) {
    super(parent,([] as any[]),([] as any[]));
  }
  createInternal():import1.ParallaxModule {
    this._ParallaxModule_0 = new import1.ParallaxModule();
    return this._ParallaxModule_0;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import1.ParallaxModule)) { return this._ParallaxModule_0; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const ParallaxModuleNgFactory:import0.NgModuleFactory<import1.ParallaxModule> = new import0.NgModuleFactory<any>(ParallaxModuleInjector,import1.ParallaxModule);
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvSWJieS9XZWJzdG9ybVByb2plY3RzL2lvbmljLXBhcmFsbGF4L3NyYy9wYXJhbGxheC5tb2R1bGUubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vQzovVXNlcnMvSWJieS9XZWJzdG9ybVByb2plY3RzL2lvbmljLXBhcmFsbGF4L3NyYy9wYXJhbGxheC5tb2R1bGUudHMiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OyJ9
